### ISSUE TITLE
Enable continuous delivery of releases to public Docker registry

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#11]
Building upon #10, when we create a new release in github, the Docker image should be built and published into the public Docker registry. 

A Docker image can be pushed using the Travis deploy 'script' task. There are two cases to be considered: 

**Release**

For a release build, this is identified as being a 'tag' build. See the documentation here: https://docs.travis-ci.com/user/deployment/releases/#deploying-only-on-tagged-builds

This would something like this: 

```
deploy:
  provider: script
  ...
  draft: false
  on:
    tags: true
```

For a tagged build, the docker image tag should be `kabanero-operator:<tag>`

**Draft Release**

Travis also supports a subselector for "draft releases": 
```
deploy:
  provider: script
  ...
  draft: true
```

When draft is set, this is considered a "release candidate" build, and the Docker tag should instead be: `kabanero-operator:<version>-RC`
