### ISSUE TITLE
Allow the same pipeline name to be used for more than one Appsody Collection.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#114]
A current limitation of the Kabanero operator requires that collection pipelines be uniquely named.  This limitation makes managing the collection pipelines difficult when the same pipeline could (and should) be used to support multiple collections.

**Comment by stephenkinder** [comment]
@kaczyns pointed out that in addition to the Pipeline artifacts in the collection, there are other resources in the collection that might also be sources of conflict.  Ideally, we need to articulate each artifact in the collections and have an approach for disambiguating reuse where appropriate.

**Comment by kyleschlosser** [comment]
@stephenkinder @smcclem I am working on a solution which allows you to incorporate directives into the yaml. This prevents us from needing a new requirement on the collection format. 

**Here is an example:** 
```
#Kabanero! on activate substitute CollectionName for text '${collection-name}'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ${collection-name}-build-deploy-pipeline
spec:
  resources:
  - resource1
  tasks:
    - name: build-task
      taskRef:
        name: ${collection-name}-build-task
```

The directive `#Kabanero! on activate substitute CollectionName for text '${collection-name}'` tells the rendering engine to replace the text '${collection-name}' with the name of the collection at activation time. 

Currently, only text substitution is allowed, and CollectionName is the only recognized replacement.
