### ISSUE TITLE
Improve KAppNav status reporting

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#214]
Currently the status reporting for KAppNav just checks to see if it could find the default KAppNav instance.  Since KAppNav is an optional component, the operator can't detect whether it's required or not.  However it should make a better attempt to:
1) determine the version of kappnav (at least report the tag of the container in the pod)
2) determine that it's `ready` by looking at the pod's status and/or conditions
3) go find the route and get the URL that should be used

**Comment by mezarin** [comment]
If kAppNav is not enabled, you get this status message:
```
status:
  kappnav:
    errorMessage: 'Could not detect the status of KAppNav: no matches for kind "KAppNav"
      in version "charts.helm.k8s.io/v1alpha1"'
    ready: "False"
```
The message is accurate, but a bit misleading.
We should also consider not showing the kappnav status if kAppNav was not installed/deployed.
