### ISSUE TITLE
Kabanero upgrade to 0.2.0 shows Kabanero status as version 0.1.0

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#219]
After upgrading to Kabanero 0.2.0, I looked at the Kabanero status and see:
```yaml
status:
  kabaneroInstance:
    ready: 'True'
    version: 0.1.0
```
I am not sure what it said on version 0.1.2, but it's definitely wrong for version 0.2.0.  Here is the current spec:
```yaml
spec:
  collections:
    repositories:
      - activateDefaultCollections: true
        name: incubator
        url: >-
          https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
  version: 0.2.0
```
