### ISSUE TITLE
Collection upgrade does not automatically activate new versions of an existing collection

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#220]
Currently when the collection URL changes (for example:)
old:
```yaml
spec:
  collections:
    repositories:
    - activateDefaultCollections: true
      name: incubator
      url: https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
```
new:
```yaml
spec:
  collections:
    repositories:
    - activateDefaultCollections: true
      name: incubator
      url: https://github.com/kabanero-io/collections/releases/download/v0.2.0-beta2/kabanero-index.yaml
```
the kabanero controller will iterate the collections in the index to make sure they exist.  However it does not make sure that the versions are correct.  The current behavior is more or less summarized in this PR:
https://github.com/kabanero-io/kabanero-operator/pull/93

I spoke with @stephenkinder today and we agreed that this behavior is not appropriate at this point.  If the collection URL changes, the updated collections should be loaded.  This means the kabanero controller should update the version in the `kind: Collection` when it detects a new one.  The collection controller will then process the upgrade immediately.  

The goal (not yet, but eventaully) will be to allow both versions of the collection to be active at the same time.  For now, we need to be sure to update the version in the collection when we detect that it has changed.
