### ISSUE TITLE
Support activating pipelines in an alternate namespace

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#230]
There is a desire to have the collection-level resources (ie pipelines, tasks, etc) deployed in a separate namespace from the rest of Kabanero.  Consider the following proposed yaml:
```yaml
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.3.0"
  targetNamespaces:
  - ns1
  - ns2
  pipelinesNamespace: kabanero-build
```
Note the new `pipelinesNamespace` attribute (name subject to change, and also cardinality, but lets go with this for now).  When activating the collections, the resources would get created in this alternate namespace.  If `pipelinesNamespace` were not specified, we would continue to activate in the current namespace (kabanero in this case).

It's not clear whether the collection itself should be activated in the current (kabanero) namespace or in the pipelines namespace.  If it's activated in the pipelines namespace, then the CLI services will need to change to watch/create `kind: Collection` instances in the pipelines namespace rather than the current namespace.  The kabanero-operator already sets up an environment variable to tell the CLI service what namespace to watch, and it may be as simple as just changing that to a new value, but that also may have un-intended side effects on the CLI, and also would probably require a new role / cluster role, to allow the CLI to search and create `kind: Collection` objects across namespaces.
