### ISSUE TITLE
Operator install to include kabanero-webhook

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-operator#237]
We are adding a new container kabanero-webhook, and it needs to be installed with kabanero operator.

**Comment by kaczyns** [comment]
@mchenggit do you need a service/route for your new container?  If so, is it HTTP or HTTPS, and do you need it to have a specific path component (after the hostname)?

**Comment by mchenggit** [comment]
It will be https.

If you can route to us without path component, then we don't need it. Otherwise, please add "/webhook".   The external URL will be:   https://<host>:<port>/webhook/<rest of path>

**Comment by kaczyns** [comment]
I've created a kabanero-operator image that supports what you sent.  You'll need to try it out and let me know if it's close to what you need.

1) Install kabanero-foundation, any version
2) `oc set image -n kabanero deployment/kabanero-operator kaczyns/kabanero-operator:webhook-phase0`
3) Edit your Kabanero CR instance to be `version: 0.3.0` and `Spec.Webhook.Enabled: true`.

Example Kabanero CR instance:
```yaml
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
  namespace: kabanero
spec:
  collections:
    repositories:
      - activateDefaultCollections: true
        name: incubator
        url: >-
          https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
  webhook:
    enable: true
  version: 0.3.0
```

Let me know when you've had a chance to try this.  The branch where I've made these changes is here:
https://github.com/kaczyns/kabanero-operator/tree/webhook
