### ISSUE TITLE
Set up liveness probe Yaml for CLI Pod

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-operator#268]
```
livenessProbe:
            httpGet:
              path: /v1/liveliness
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
```
