### ISSUE TITLE
Duplicate KnativeEventing instance when deploying a Kabanero instance

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#27]
When deploying a Kabanero instance, a KnativeEventing instance is created.  The status of that instance reports:
```yaml
    - lastTransitionTime: '2019-07-09T14:53:32Z'
      message: >-
        Install not attempted: The only KnativeEventing resource that matters is
        knative-eventing/knative-eventing
      reason: Ignored
      status: 'False'
      type: Ready
```
We probably need to stop creating that resource by default, and if we have something specific we need, patch the existing resource in the knative-eventing namespace rather than try to create our own resource.
