### ISSUE TITLE
Extend the Kabanero Collection CRD to allow multiple stack versions to be active simultaneously.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-operator#288]
Document the design for the Kabanero Collection CRD schema to support multiple versions of the same Kabanero Collection to be active at the same time.

**Comment by kaczyns** [comment]
I'm proposing the following CR instance structure, which maintains all
of the fields that exist prior to now, as well as the new array that
will allow us to enable multiple versions of the same collection at
the same time:

```yaml
apiVersion: kabanero.io/v1alpha1
kind: Collection
metadata:
  name: java-microprofile
  namespace: kabanero
spec:
  name: java-microprofile
  desiredState: active
  repositoryUrl: https://whatever.com/blah/blah
  version: 0.2.15
  versions:
  - version: 0.2.15
    desiredState: active
    repositoryUrl: https://whatever.com/blah/blah
  - version: 0.2.16
    desiredState: active
    repositoryUrl: https://whatever.com/blah/blah
  - version: 0.2.17
    desiredState: active
    repositoryUrl: https://whatever.com/blah/blah
status:
  activeLocation: https://whatever.com/blah/blah
  activePipelines:
  - name: default
    digest: abc123
    url: https://whatever.com/common.pipeline.default.tar.gz
    activeAssets:
    - assetDigest: efg456
      assetName: ./build-pipeline.yaml
      status: active
    - assetDigest: try934
      aseetName: ./some-other.yaml
      status: active
    activeVersion: 0.2.15
    images:
    - id: java-microprofile
      image: kabanero/java-microprofile:0.2
    status: active
  activeVersions:
  - location: https://whatever.com/blah/blah
    pipelines:
    - name: default
      digest: abc123
      url: https://whatever.com/common.pipeline.default.tar.gz
      assets:
      - assetDigest: efg456
        assetName: ./build-pipeline.yaml
        status: active
      - assetDigest: try934
        aseetName: ./some-other.yaml
        status: active
      version: 0.2.15
      images:
      - id: java-microprofile
        image: kabanero/java-microprofile:0.2
      status: active
  - location: https://whatever.com/blah/blah
    pipelines:
    - name: default
      digest: abc123
      url: https://whatever.com/common.pipeline.default.tar.gz
      assets:
      - assetDigest: efg456
        assetName: ./build-pipeline.yaml
        status: active
      - assetDigest: try934
        aseetName: ./some-other.yaml
        status: active
      version: 0.2.16
      images:
      - id: java-microprofile
        image: kabanero/java-microprofile:0.2
      status: active
  - location: https://whatever.com/blah/blah
    pipelines:
    - name: default
      digest: abc123
      url: https://whatever.com/common.pipeline.default.tar.gz
      assets:
      - assetDigest: efg456
        assetName: ./build-pipeline.yaml
        status: active
      - assetDigest: try934
        aseetName: ./some-other.yaml
        status: active
      version: 0.2.17
      images:
      - id: java-microprofile
        image: kabanero/java-microprofile:0.2
      status: active
```

Note that only `spec.versions` and `status.activeVersions` are new.
The versions[0] duplicates the former singleton values, and
activeVersions[0] duplicates the former singleton status values.  This
mapping is required so that older clients can continue to function.
Our intention will be to introduce a new version of the CRD which
eliminates the singleton versions of these fields, and deprecate this
one.  I am proposing `v1alpha2` as the new version.

A CRD has a conversion strategy.  Currently in OCP 4.2 `none` is the
only supported strategy.  This means that the fields between CRD
versions need to line up exactly.  This is why the `v1alpha1` CRD has
to have exactly the same field names as the `v1alpha2` CRD will have.
In OCP 4.3, we will be able to use a conversion webhook to avoid this,
however it will be some time before OCP 4.3 is a prerequisite.  See:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md
and
https://v1-14.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#webhook-conversion

The resulting CRD is large and unwieldy but will allow products built
on Kabanero to continue to function while we make the conversion.  The
next version of Kabanero can introduce a v1alpha2 CRD which is served
but not stored, and only contains the new fields.  Then in a future
release of Kabanero, we can store the v1alpha2 version, and finally in
another future release of Kabanero we can remove the v1alpha1 CRD
altogether.

We will require an admission webhook (see #57) to enforce that the
singleton `spec.version` field does not contradict the array form
`spec.versions`.  There are two admission webhook types - validating
and mutating.  A mutating webhook can change values, while a
validating webhook can not.  I would propose that we have a mutating
web hook which makes sure that the singleton version represents the
first item in the versions array.  Then the validating webhook makes
sure that the singleton and the first item in the version array
match.  Things get tricky when the user updates the CR instance - see
the "Params" and "HeightInInches" examples in the `api_changes.md`
link above.  We will need to compare the "old" and "new" version of
the object to see what changed, and make sure the mapping between
`version` and `versions[0]` is consistent.

This comment does not address the desire (or requirement) to re-name
the collection resources (pipelines, tasks, etc) so that they can be
re-used across collection versions.  I'll make an additional comment
with a proposal on that.
