### ISSUE TITLE
Add digest as a directive on the collection directive processor

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#308]
In support of #288 
Collections can use directives in the first line of an asset to instruct the collection controller to make a substitution. For example:
```
#Kabanero! on activate substitute CollectionId for text 'CollectionId'
```
Will replace the text `CollectionId` in the yaml, with the ID of the collection that is being applied.  Here is a collection asset that uses this:
https://github.com/kabanero-io/kabanero-pipelines/blob/bf98716083a5a66fa03aa7372015140ec00be0d5/pipelines/incubator/deploy-task.yaml

Currently, `CollectionName` and `CollectionId` are supported, although CollectionName is of little use in Kubernetes since it can contain unsupported characters.  We should add a third supported value, `Digest`.  The digest will resolve to the first 8 characters of the SHA256 for the pipeline zip containing the asset.  If a pipeline zip has a SHA256 of `abcdef0123456789` and the following asset exists in the zip:
```yaml
#Kabanero! on activate substitute Digest for text 'Digest'
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-task-Digest
spec:
  inputs:
    resources:
    - name: git-source
...
```
then Kabanero would create a `kind: Task` with name `deploy-task-abcdef01`.  And so on for each asset in the collection.  Each asset in the collection (pipeline zip) would use the same digest since they all come from the same zip.

Method `process_directive` in `directive_processor.go` takes a context map as input, and the first 8 characters of the SHA256 for the pipeline zip will need to be added to the map, using `Digest` as the key, so that the processor can make the substitution.
