### ISSUE TITLE
Kabanero CSV owned CRD resources is not correct

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#31]
The kabanero-operator CSV says that the `Kabanero` CRD owns the following resources:
```yaml
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      - kind: Deployment
        name: ""
        version: v1
      - kind: Pod
        name: ""
        version: v1
      - kind: Role
        name: ""
        version: v1
      - kind: RoleBinding
        name: ""
        version: v1
      - kind: ServiceAccount
        name: ""
        version: v1
```
This is not correct - the Kabanero operator creates a Tekton `Install`, a Knative `KnativeEventing` and a Knative `KnativeServing`.  

The OKD / OpenShift console uses the `resources` section as a clue for what to display when viewing an instance of our CRD.  It's not broken the way it is, but it's not useful either.
