### ISSUE TITLE
Operator need to deactivate/remove the collection after collection hub is updated to remove a collection

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#315]
Operator does not deactivate/remove the Collection even after kabanero CLI `sync` command is used.

* Removed the node.js collection directory from cloned kabanero collections.
* Build collections and released them at https://github.com/mtamboli/collections/releases/tag/v0.3.9
* Updated operator (CR instance) to pick up new collection
```
collections:
    repositories:
      - activateDefaultCollections: true
        name: central
        url: >-
          https://github.com/mtamboli/collections/releases/download/v0.3.9/kabanero-index.yaml
  github:
    apiUrl: 'https://api.github.ibm.com'
    organization: was-svt
    teams:
      - svt-kab
```
```
 ./kabanero sync

Kabanero Instance Collections	Version	Status
-----------------------------	-------	------
nodejs				0.2.6	deactivated
i$ ./kabanero list

Kabanero Instance Collections	Version	Status
-----------------------------	-------	------
java-ee				0.1.1	active
java-microprofile		0.2.19	active
java-spring-boot2		0.3.16	active
nodejs				0.2.6	active
nodejs-express			0.2.8	active
nodejs-loopback			0.1.6	active
nodejs				0.2.6	obsolete

GitHub Curated Collections	Version
--------------------------	-------
java-ee				0.1.1
java-microprofile		0.2.19
java-spring-boot2		0.3.16
nodejs-express			0.2.8
nodejs-loopback			0.1.6
image
```
**Still have the old collection active:**

```
spec:
  desiredState: inactive
  name: nodejs
  repositoryUrl: >-
    https://github.com/mtamboli/collections/releases/download/v0.3.5/kabanero-index.yaml
  version: 0.2.6
status:
  activeLocation: >-
    https://github.com/mtamboli/collections/releases/download/v0.3.5/kabanero-index.yaml
  activePipelines:
```
