### ISSUE TITLE
Better error message when any of the resource zip does not exist 

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#341]
There were some issues with building collections where the index file was pointing to the pipeline zip file which was not existing. In this case, operator gave some checksum error which was not helpful to the user. If operator indicated the file was not existing, it will help user figure out the issue.
```
{"level":"error","ts":1575407586.319056,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"collection-controller","request":"kabanero/nodejs","error":"Index checksum: 03bf2e4bb56e489a4c6c7b759dd3037a40055ee9cb58a97ea200477594b3caba not match download checksum: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5","stacktrace":"github.com/kabanero-io/kabanero-operator/vendor/git
```
```
pipelines:
  - id: default
    sha256: 03bf2e4bb56e489a4c6c7b759dd3037a40055ee9cb58a97ea200477594b3caba
    url: https://github.com/kabanero-io/collections/releases/download/v0.4.1/incubator.common.pipeline.default.tar.gz
```
`incubator.common.pipeline.default.tar.gz` URL is wrong
