### ISSUE TITLE
Add v1alpha2 and Stack CRDs

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#386]
We have received feedback from users that the idea of an Appsody stack and a Kabanero collection being the same thing, is confusing.  A brief overview - a Kabanero collection starts as an Appsody stack, to which we add additional configuration for Kabanero such as pipelines, triggers and image names.  The app developer generally uses Appsody (and an appsody stack) to develop an application, while operations is using Kabanero (and Kabanero collections) to deploy the applications to test and production.

The Kabanero controller should be taught how to read an Appsody stack, with the additional bits and pieces required by Kabanero specified in the Kabanero CR instance, rather than in the Appsody stack.  To this end, we should work towards a v1alpha2 of the Kabanero CRD.  The Collection CRD should be re-named to the Stack CRD to better reflect what it will actually be.

See:
https://github.com/kabanero-io/roadmap/issues/126

**Comment by kaczyns** [comment]
I am proposing the following for the Kabanero v1alpha2 CRD (I'm going to write out a complete CR instance to show all of the fields, I think this is more consumable than listing the schema from the CRD)
```yaml
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.6.0"
  stacks: 
    repositories: 
    - name: central
      url: https://github.com/kabanero-io/stacks/releases/download/0.6.0/index.yaml
      skipCertVerification: false  // default is false
    - name: incubator
      url: https://github.com/kabanero-io/stacks/releases/download/0.7.0/index.yaml
      skipCertVerification: false  // default is false
  targetNamespaces:
    - test1
    - deploy1
  github:
    organization: kabanero-io
    apiUrl: http://api.github.com
    teams:
      - admin
      - operations
  pipelines:
    - id: default
      sha256: 0123456789abcdef
      url: https://github.com/kabanero-io/pipelines/releases/download/0.7.0/default.pipeline.tar.gz
  triggers:
    - id: default
      sha256: 0123456789abcdef
      url: https://github.com/kabanero-io/triggers/releases/download/0.7.0/default.triggers.tar.gz
  cliServices:
    version: x.y
    image: kabanero/kabanero-command-line-services:0.6.0
    repository: kabanero
    tag: "0.6.0"
    sessionExpirationSeconds: 1440s
  landing:
    enable: true
    version: x.y
  che:
    enable: false
    cheOperatorInstance:
      cheWorkspaceClusterRole: codewindRole
    kabaneroChe:
      version: x.y
      image: kabanero/kabanero-che:0.6
      repository: kabanero
      tag: "0.6.0"
  events:
    enable: false
    version: x.y
    image: kabanero/kabanero-events:0.1
    repository: kabanero
    tag: "0.1"
  stackController:
    version: x.y
    image: kabanero/kabanero-operator-stack-controller:0.6.0
    repository: kabanero
    tag: "0.6.0"
  admissionControllerWebhook:
    version: x.y
    image: kabanero/kabanero-operator-admission-webhook:0.6.0
    repository: kabanero
    tag: "0.6.0"
```
Note specifically, the added `pipelines` and `triggers` sections.  This CRD does not attempt to give a way to over-ride a pipeline or trigger at the stack version level.  We need to find a way to do this.

**Comment by kaczyns** [comment]
I am proposing the following Stack CRD for v1alpha2.  Same format - this is a fully specified Stack CR instance:
```yaml
apiVersion: kabanero.io/v1alpha2
kind: Stack
metadata:
  name: java-microprofile
spec:
  name: java-microprofile
  versions:
    - repositoryUrl: https://github.com/kabanero-io/stacks/releases/download/0.6.0/index.yaml
      pipelines:
        - id: default
          url: https://github.com/kabanero-io/pipelines/releases/download/0.6.0/default.pipeline.tar.gz
          sha256: 0123456789abcdef
      version: "0.2.15"
      desiredState: ""
      skipCertVerification: false
      images:
        - id: java-microprofile
          image: docker.io/kabanerobeta/java-microprofile:0.2
    - repositoryUrl: https://github.com/kabanero-io/stacks/releases/download/0.7.0/index.yaml
      pipelines:
        - id: default
          url: https://github.com/kabanero-io/pipelines/releases/download/0.7.0/default.pipeline.tar.gz
          sha256: 0123456789abcdef
      version: "0.2.21"
      desiredState: ""
      skipCertVerification: false
      images:
        - id: java-microprofile
          image: docker.io/kabanerobeta/java-microprofile:0.2
```
Note specifically the pipelines and images are now specified in the collection spec.  The Kabanero controller would have read these out of the Kabanero CR instance, and copied them here so the stack controller can process them.

**Comment by groeges** [comment]
@kaczyns Are these CRDs going to be automatically generated or generated and edited by hand?

In the stack CRD where are you intending to get the image information from, ie.
```
      images:
        - id: java-microprofile
          image: docker.io/kabanerobeta/java-microprofile:0.2
```
this is currently added to the index.yaml by the kabanero build scripts (from the collection.index). If we are moving to appsody hubs and using the index.yamls that are generated as part of their builds then this info will not be available?

**Comment by kaczyns** [comment]
@groeges yes I realize that the information will not be available from the appsody hub.... we have to learn how to generate it in the operator and insert it into the CRD, so that the build pipeline can retrieve it and check to see if the stack is active.

**Comment by kaczyns** [comment]
@stephenkinder suggested that the `pipeline` and `triggers` sections live inside the `stacks` section of the Kabanero CRD, since at some point later we may want to introduce pipelines that are not associated with stacks (all of the existing pipelines and triggers are associated with stacks).  I am going to update the first comment to reflect this.

**Comment by groeges** [comment]
@kaczyns We are looking at adding the image element to the generated appsody index.yaml.
It would not be the same format as currently used in the kabanero index yaml but would just be something like:
```
image: docker.io/kabanerobeta/java-microprofile:0.2
```
and will be provided for each stack listed in the index yaml. 
Hopefully this will enable you to provide the same functionality in the operator as you do today.

**Comment by kaczyns** [comment]
Cheers for that Steve.  We appreciate not having to figure out how to build that ourselves.

**Comment by jgawor** [comment]
I'm trying to understand something here. The operator takes in a list of stack repositories and pointers to pipelines, triggers, etc. and creates and maintains the `Stack` resources. Why not drop all of that and just let Champ create and manage the `Stack` resources directly. Each `Stack` object could be specific to a particular version and have Stack specific links. With this, the CLI tools and IDEs could also be extended to "discover" enabled `Stacks` just by using the Kubernetes API. This would eliminate the need for building and maintaining a static index file and make things more dynamic in terms of discovery what `Stacks` are enabled (i.e. per namespace), etc.

**Comment by kaczyns** [comment]
@jgawor Champ can certainly do that if he wants to.  He can leave the repositories section of the Kabanero CR instance empty.  We are going to document this pattern.

The CLI already "discovers" `Collection` instances and will discover `Stack` instances as well (this is how the sync function works).

**Comment by jgawor** [comment]
But why have two different patterns to maintain?

When I look at the proposed `Stack` definition it specifies `repositoryUrl` which points to some `index.yaml` file. I assume that's Appsody's `index.yaml` which could contain multiple stack definitions. And I guess that url was used to load the `Stack` metadata. But if I'm working with a single `Stack`, I might not have an `index.yaml` file and I shouldn't need to create one.

The `kabanero` CLI does but I was thinking about `appsody` CLI.

**Comment by kaczyns** [comment]
You're right - it doesn't make any sense to have the `repositoryUrl` in the `Stack` CR definition.  In the case where the Stack was created by the Kabanero controller, we thought it would be beneficial to know why the Kabanero controller created that stack (what index did it read).  but it probably just makes it more confusing.  @stephenkinder and I just talked about it and we'll take it out.

**Comment by jgawor** [comment]
I would also propose that any references to GitHub be changed to use GitHub API. For example instead of 
```
      pipelines:
        - id: default
          url: https://github.com/kabanero-io/pipelines/releases/download/0.7.0/default.pipeline.tar.gz
          sha256: 0123456789abcdef
```
The `Stack` would support something like:
```
      pipelines:
        - id: default
          github:
             url: https://github.com/kabanero-io/kabanero-pipelines
             revision: 0.5.0 (defaults to master)
```
Or something similar if we want to support using the GitHub release API. The operator would lookup credentials for such endpoints using the same way as [Tekton](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md). This would provide GitHub Enterprise support and potentially add ability to point to the latest release of pipelines `0.2` just like the Stack image does.

This method could also be extended to support various other protocols later on. For example:

```
      pipelines:
        - id: default
          http:
             url: https://github.com/kabanero-io/pipelines/releases/download/0.7.0/default.pipeline.tar.gz
             skipCertVerification: false
             sha256: 0123456789abcdef
```

**Comment by kaczyns** [comment]
@stephenkinder could you comment on Jarek's comment above please, about GHE?  You had asked us in #253 to consider the GHE case holistically across all of the other products (ie appsody).  Does Jarek's proposal fit with what you had in mind?  If we are going to do something like that, then all of the following need to change:
1) stack index yaml in Kabanero CR
2) pipelines tar gz in Stack CR
3) triggers tar gz in Kabanero CR

These changes would also have implications for CLI, landing page, and eventing, since they would need to be able to read the CR and access the files in the same way.

**Comment by stephenkinder** [comment]
@kaczyns @jgawor So I do like the idea of transitioning to _github_ specific syntax suggested by Jarek.   That said, we already have a ton of work to try to get done in 0.6.0.  Do we hate the idea that one could use a URL or GitHub?  In other words, can we add the GitHub syntax as a formal epic and deliver a future milestone?  As Tim says, it is fairly pervasive -- the 0.6.0 cup overfloweth. 

To be clear, the idea is to leave _URL:_ for now and add the GitHub spelling as a separate future change?

**Comment by kaczyns** [comment]
I like that - for now we'd have:
```yaml
spec:
  versions:
    pipelines:
      - id: default
        sha256: abcdef0123456789blahblabhblah
        https:
          url: https://github.com/kabanero-io/pipelines/releases/download/0.7.0/default.pipeline.tar.gz
          skipCertVerification: false
```
and then later we'd add `spec.versions.pipelines.github.blahblah`
Yes?
