### ISSUE TITLE
Directive processor needs to handle StackId

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#389]
The kabanero directive processor (`directive_processor.go`) replaces certain strings in the pipeline zip artifacts, with other things.  For example. if the text `CollectionId` is present in the yaml, with an appropriate directive, then `CollectionId` is replaced with the Id of the collection (ie java-microprofile).

We need to support `StackId`, which should function the same as `CollectionId`.  While there is a `CollectionName` also, we should not add `StackName` since the field can contain UTF characters which are not accepted in a Kubernetes object name.

This may end up being a simple change in `collection_controller.go` to add an additional key to the `renderingContext`, and some additional test cases.

While we're doing this, we should also add test cases that support having two directives in the same YAML file.  For example, specifying `StackID` and `Digest` together like this:
```yaml
#Kabanero! on activate substitute StackId for text 'StackId'
#Kabanero! on activate substitute Digest for text 'Digest'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: CollectionId-build-pipeline-Digest
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
```
This should produce something like `java-microprofile-build-pipeline-01234567.
