### ISSUE TITLE
Retrieve release assets from GHE

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#469]
Given a Github HTTP client (see #467 ) retrieve a release asset from GHE.  The asset could be a yaml file or a zipped tarball (index or pipeline zip).

The following modifications should be made to the Kabanero CRD to accommodate for the additional parameters necessary when using the Github API (see this example CR instance):
```yaml
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.6.0"
  stacks: 
    repositories: 
      - name: central
        githubRelease:
          hostname: github.mydomain.com
          organization: myOrg
          project: myProject
          release: myRelease
          assetName: incubator-index.yaml
```
Note that the `githubRelease` is mutually exclusive with the existing `https`.  Only one or the other should be specified.  The `githubRelease` stanza includes all of the information necessary to use the github API to retrieve a release asset.  We could consider having another way of specifying all of this information (ie a `url` field that specifides `https://github.mydomain.com/myOrg/myProject/releases/download/myRelease/incubator-index.yaml`) but for now lets list it out explicitly as the github API requires it.

This is the Github Go client:
https://godoc.org/github.com/google/go-github/github#Client

The `Repositories` member provides access to the releases and their assets.  The following appears to download a release asset:
https://godoc.org/github.com/google/go-github/github#RepositoriesService.DownloadReleaseAsset

You need to know the `id` of the asset that you want to get.  This may require some digging:
https://godoc.org/github.com/google/go-github/github#RepositoriesService.GetReleaseByTag
to get the release ID. 
https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListReleaseAssets
to match the asset name to the asset ID.

If there is an easier way to do this, I'm all for it.  I don't think we can just jam a request in for the whole URL, but if we can we should do that, it's probably easier.  That is, just use the Github HTTP client but pass in the URL to the asset that we want.  I don't think that will work, but if it does, great.

Another issue will integrate the HTTP request/response that we use to retrieve the release asset, with the cache that we maintain.  This assumes that Github continues to use `etags` when using this API.
