### ISSUE TITLE
update default.yaml to use kabanero-stack-hub repository

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-operator#517]
The fix for https://github.com/kabanero-io/collections/issues/282#issuecomment-589530603 provides a new url for kabanero stackhub https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.0-rc.1/kabanero-stack-hub-index.yaml
Please update the https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.6.0-rc.4/config/samples/default.yaml with the new url.   
Right now it still points to https://github.com/kabanero-io/collections/releases/download/0.6.0-rc.1/kabanero-index.yaml

**Comment by marikaj123** [comment]
@tam512 - the new url: https://github.com/kabanero-io/kabanero-stack-hub/releases/tag/0.6.0-rc.2

**Comment by mezarin** [comment]
FYI. The code delivered under PR 520 is already in v0.6.0-rc5. PR 520 is a delivery to master.

**Comment by tam512** [comment]
verified the problem is fixed in https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.6.0-rc.5/config/samples/default.yaml
```
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.6.0"
  stacks: 
    repositories: 
    - name: central
      https:
        url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.0-rc.2/kabanero-stack-hub-index.yaml
    pipelines:
    - id: default
      sha256: 147455156595e8ad95e71ee712e4066eeb0225903847b3ac04a59e69ba899f60
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0-rc.6/default-kabanero-pipelines.tar.gz
```
