### ISSUE TITLE
Kabanero 0.7.0 can't find the `knative-serving` instance

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#526]
From the Kabanero CR instance status:
```yaml
  serverless:
    knativeServing:
      message: Knative serving instance with the name of knative-serving under the
        namespace of knative-serving could not be found.
      ready: "False"
    ready: "False"
    version: 1.4.1
```
The name of the KnativeServing CRD changed in Serverless 1.4.x and we likely need to be looking for the new name.
