### ISSUE TITLE
Allow admission-webhook and stack controller image to default to operator image

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#552]
Today, when we cut a new release of kabanero-operator, we have to make changes to `config/versions.yaml` and replace the container tags for the admission webhook and stack controller (and collection controller).  Each manual step that is performed during a release is another opportunity for something to go wrong.

The admission webhook and stack controller are almost always built at the same time as the operator itself (they are built from the same `Makefile`).  We should introduce a way to tell the operator that it should use the same repository and/or tag for itself, that the operator is using.

The operator can get the yaml for its own pod to pull out its image name (the pod name is already exported as an environment variable in the deployment template in the CSV).  The operator can then parse the image name, taking the tag (everything past the last colon) and repository (everything before the last colon).  The first part of the repository can be changed such that `kabanero-operator` can become `kabanero-operator-admission-webhook` or `kabanero-operator-stack-controller`.

How should we tell the operator to do this?  I'm proposing that in the `versions.yaml`, for the current version, we can give a repository and tag of "FROM_POD" and that would be a clue to the operator to take this information from the currently running kabanero-operator pod.  Any component that wants to do this would also need to provide their container name so that we can substitute it for `kabanero-operator`.

For example:
```yaml
default: "0.7.0"
kabanero:
- version: "0.7.0"
  related-versions: 
    stack-controller: "0.7.0"
    admission-webhook: "0.7.0"
related-software:
  stack-controller:
  - version: "0.7.0"
    orchestrations: "orchestrations/stack-controller/0.1"
    identifiers:
      repository: "FROM_POD"
      tag: "FROM_POD"
      container: "kabanero-operator-stack-controller"
  - version: "0.6.0-rc.6"
    orchestrations: "orchestrations/stack-controller/0.1"
    identifiers:
      repository: "kabanero/kabanero-operator-stack-controller"
      tag: "0.6.0-rc.6"
  admission-webhook:
  - version: "0.7.0"
    orchestrations: "orchestrations/admission-webhook/0.2"
    identifiers:
      repository: "FROM_POD"
      tag: "FROM_POD"
      container: "kabanero-operator-admission-webhook"
  - version: "0.6.0-rc.6"
    orchestrations: "orchestrations/admission-webhook/0.2"
    identifiers:
      repository: "kabanero/kabanero-operator-admission-webhook"
      tag: "0.6.0-rc.6"
```

It's open for debate whether the `FROM_POD` strings should be resolved initially when the version info is read, or when someone tries to get the image.

At runtime, if the env-var `POD_NAME` is set to `kabanero-operator-abcdefg` then the code would query the pod and pull out the container name from the yaml, something like `kabanero/kabanero-operator:0.7.0-alpha.1`.  It would parse out the tag as `0.7.0-alpha.1` and the repository as `kabanero/kabanero-operator`.  For the admission controller we'll substitute `kabanero-operator` for `kabanero-operator-admission-webhook` and end up with `kabanero/kabanero-operator-admission-webhook:0.7.0-alpha.1`.  

An alternative (simpler) approach would be to put the admission controller and stack controller executables in the same container image as the operator, and then we can literally just use the same container image.  Maybe that's easier?
