### ISSUE TITLE
Install OpenShift ServiceMesh Operator 1.0.8

### ISSUE THREAD

**Issue by csantanapr** [kabanero-io/kabanero-operator#553]
ServiceMesh Operator 1.0.8 is a new version that contains fixes to work out of of the box when using Managed OpenShift 4.3 on IBM Public Cloud.

https://github.com/Maistra/istio/releases/tag/maistra-1.0.8

kabanero operator registry/catalog 0.6 installs version 1.04
https://github.com/kabanero-io/kabanero-operator/blob/0.6.0/registry/manifests/servicemeshoperator/servicemesh.package.yaml#L8

kabanero operartor registry/catalog 0.7 installs 1.0.7
https://github.com/kabanero-io/kabanero-operator/blob/0.7.0-alpha.1/registry/manifests/servicemeshoperator/servicemesh.package.yaml#L10

**Comment by kaczyns** [comment]
@csantanapr Kabanero 0.6.1-rc.1 is available for you to verify with, when you are ready.

**Comment by marikaj123** [comment]
@kaczyns - Was the fix for this issue included into 0.6.1-rc.1?  If yes, can we get this issue verified and closed, please?

**Comment by csantanapr** [comment]
I tried the installer 0.6.1-rc.1 and see some problems, please clarify
https://github.com/kabanero-io/kabanero-operator/releases/tag/0.6.1-rc.1

At the end is printing a message to use the collection/stack hub 0.6.0
```
***************************************************************************
*
*  The installation script is complete.  You can now create an instance
*  of the Kabanero CR.  If you have cloned and curated a collection set,
*  apply the Kabanero CR that you created.  Or, to create the default
*  instance:
*
*      oc apply -n kabanero -f https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.6.1-rc.1/config/samples/default.yaml
*
***************************************************************************
```

When I inspect the `deafult.yaml`
```
cat default.yaml
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.6.1"
  stacks:
    repositories:
    - name: central
      https:
        url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.0/kabanero-stack-hub-index.yaml
    pipelines:
    - id: default
      sha256: abbc2ed0e19349aa5e23b511b75449fb1a515cfd6a548b05b6516fb7c6de1aba
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0/default-kabanero-pipelines.tar.gz
```

I think this should point to 0.6.1 not 0.6.0?
https://github.com/kabanero-io/kabanero-stack-hub/releases/tag/0.6.1
