### ISSUE TITLE
Update the collection status

### ISSUE THREAD

**Issue by kyleschlosser** [kabanero-io/kabanero-operator#62]
The collection needs a status which reflects both the current state, version and digests of the collection but also any errors applying collection contents. A common error applying collection contents results from RBAC limitations within the collection contents. Some of the status recording needs to be per resource, while other parts are per collection. 

Example: 

```
status:
    # Here available version > current reflects an available update
    availableVersion: 1.0.0.1
    currentVersion: 1.0.0.0
    resources:
    - name: <resource name or path>
      currentDigest: <digest>
      status: applied
    - name: <resource name or path>
      currentDigest: <digest>
      status: failed
      statusMessage: "role" is forbidden from creating objects of kind
```

**Phases and Conditions**
Some Kubernetes objects are treated as a state machine and record their status using "phases and conditions" concepts. This allows the status to record such things as whether it is initializing, ready, failed, etc. The use of phases and conditions is advanced and optional at this point, however, some of this idea is present in the above modeling in order to account for individual resource application failures. 

For an example of this, see: 
* https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/conditions.go#L83
* https://github.com/openshift-knative/knative-eventing-operator/blob/62770a4fec0e75e81377731073c94cb3b1ca82ef/pkg/apis/eventing/v1alpha1/knativeeventing_lifecycle.go
