### ISSUE TITLE
kabanero-operator does not populate env variables correctly for GHE

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#655]
Kabanero operator defined GitHub entries which are used by CLI as well as landing page. 

landing page expects this URL to be ` apiUrl: https://github.company.com` but CLI expects it as ` apiUrl: https://api.github.company.com`. Kabanero operator need to process these env variables so both the URLs should work correctly.

```
 github:
    apiUrl: https://api.github.company.com
    organization: my-org
    teams:
    - my-team
```
