### ISSUE TITLE
Stack finalizer does not complete when unknown tekton types in pipelines

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#659]
If I have a pipeline zip, with an invalid tekton object type in it, then I get the following in my Stack CR status:
```yaml
      - assetDigest: fc451d39a3dacac4e82044d1195a5553115e5953965326bc41227c0d1bba4d6a
        assetName: java-microprofile-build-push-pl-template
        group: tekton.dev
        kind: TriggerTemplate
        namespace: tekton-pipelines
        status: unknown
        statusMessage: 'Unable to check asset: no matches for kind "TriggerTemplate"
          in version "tekton.dev/v1alpha1"'
        version: v1alpha1
```
This is a good error message.  However when I try to delete the stack, or the Kabanero CR instance, the stack controller finalizer never runs.  I suspect it's because it's trying to check and see if it needs to create this object, and it can't, because the type does not exist.  So when it checks, it gets an error every time.

Some solutions I can think of:
1) see if we can detect the "no kind" error and just assume it's not there (because the kind does not exist)
2) skip assets with `status` not equal to `active`  (need to be good about making sure the `status` is correct when the assets are activated)  (maybe can do this conditionally if the delete fails)

This is particularly a problem now, because Tekton triggers 0.4 changed the api group, and so if you try to activate old pipelines, you fall into this case (because now `TriggerTemplate` is not found in the old `apiGroup`).
