### ISSUE TITLE
New CLI service orchestration for Golang

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#705]
There is going to be a prototype of the CLI service written in Golang.  We will need a new version of the CLI service orchestration to support this.

Need to:
* Remove the init container processing from the deployment
* Make sure the secret with the service serving certificate is mounted in a way that the go code can read it and use it
* Remove any other java references from there.  Probably the health probes are hard-coded to the Liberty mpHealth endpoints.
* In `config/versions.yaml` need to make a new "version" of the CLI service that uses the new orchestration.  Probably just call it `go-prototype` or something.  Don't associate it with a high-level kabanero version.

When the CLI service team uses this, they are going to specify the orchestration version, and the `image` in the Kabanero CR instance.  Like this:
```yaml
spec:
  cliServices:
    version: "go-prototype"
    image: "kaczyns/kabanero-command-line-services:latest"
```
