### ISSUE TITLE
Need a way to tell user if there is error/warning on the stack

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-operator#719]
With digest value ready by stacks, there are cases when digest of the image cannot be read due to lack of secret or certificate trust issues. In this case, user does not know if something is wrong unless you look at each stack. Stacks show as active as well although there is an error as below.
```
status:
  summary: '[ 0.3.23: active ]'
  versions:
  - images:
    - digest:
        message: 'Unable to retrieve stack activation digest for image: <image registry>/kabsvt/svt-springboot:0.3.23.
          Associated stack: svt-springboot 0.3.23. Error: : Authentication is required'
```
```
oc get stacks
NAME             AGE     SUMMARY
svt-jmp          5m49s   [ 0.1.1: active ]
svt-springboot   5m49s   [ 0.3.23: active ]
```
Users are not able to find out if something is wrong with their stack. One option that could help will be to add another field to show Error/Warning? Thoughts?
```
svt-jmp          5m49s   [ 0.1.1: active, Error]
```

**Comment by mezarin** [comment]
Hi @mtamboli. Please see the fix for https://github.com/kabanero-io/kabanero-operator/issues/715. It attempts to address the point you bring up.

**Comment by dacleyra** [comment]
In 0.9.1-rc.1, inaccessible registry should reflect a status such as

```
status:
  summary: '[ 0.3.6: error ]'
  versions:
  - images:
    - digest:
        message: 'Unable to retrieve stack activation digest for image: default-route-openshift-image-registry.apps.dac43.mycluster.com/default/nodejs:0.3.6.
          Associated stack: nodejs 0.3.6. Error: Get https://default-route-openshift-image-registry.apps.dac43.mycluster.com/v2/:
          x509: certificate signed by unknown authority'
      id: Node.js
      image: default-route-openshift-image-registry.apps.dac43.mycluster.com/default/nodejs
```

If this is not sufficient, please reopen
