### ISSUE TITLE
stack activation digest fails to be retrieved due to certificate issues - ingress cert should be trusted by default

### ISSUE THREAD

**Issue by bconey** [kabanero-io/kabanero-operator#728]
The stack activation digest is not being retrieved from stack images in the internal OCP registry due to error `x509: certificate signed by unknown authority`.

```
.....
status:
  summary: '[ 0.3.29: active ]'
  versions:
  - images:
    - digest:
        message: 'Unable to retrieve stack activation digest for image: default-route-openshift-image-registry.apps.bfcjicpa.cp.fyre.ibm.com/kabanero/java-spring-boot2:0.3.29.
          Associated stack: java-spring-boot2 0.3.29. Error: Get https://default-route-openshift-image-registry.apps.bfcjicpa.cp.fyre.ibm.com/v2/:
          x509: certificate signed by unknown authority'
      id: Spring Boot®
      image: default-route-openshift-image-registry.apps.bfcjicpa.cp.fyre.ibm.com/kabanero/java-spring-boot2
.....
```

After some discussion, the thought is that the  Ingress certificate should be trusted by default and this error should not be seen for this setup using the internal registry.
