### ISSUE TITLE
Add devfile urls to the Stack CRD

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-operator#748]
A Stack CR may point to a devfile rather than contain appsody-style artifacts.  We will add two new fields to the `spec` section of the Stack CRD, which will link to devfile related artifacts:
```yaml
apiVersion: kabanero.io/v1alpha2
kind: Stack
metadata:
  name: my-stack
  namespace: kabanero
spec:
  name: my-stack
  versions:
    - version: 0.0.1
      pipelines: (omitted for brevity)
      desiredState: active
      devfile:
      metafile:
```
Note the `devfile` and `metafile`.  These point to the `devfile.yaml` and the `meta.yaml` respectively for a specific devfile.  I am proposing that they can be one of `https` or `gitRelease` as support currently for the pipeline zips, and for the stack hub index in the Kabanero CR instance.

The stack controller will need to make sure it's in `odo mode` before acting on a Stack CR instance with `devfile` and `metafile` set (see #747 ).  The specific actions to take are still being discussed, but for the time being:
1) The `status.version[x].version` should be set from `metadata.version` in the devfile
2) The `status.version[x].images` should be set by iterating the `components[x]` array in the devfile, and looking for elements that have a `container` set.  The `container` will have an `image` and we can retrieve the digest for that image and put it in the Stack CR status.  Note that there can be multiple images!
3) The `status.version[x].pipelines` should be set in the usual way.

There is an example devfile registry here, but note that this is subject to change:
https://github.com/elsony/devfile2-registry

Note that we are talking about v2 devfiles here.
