### ISSUE TITLE
Unable to patch and add a new pipeline to the kabanero CR

### ISSUE THREAD

**Issue by oiricaud** [kabanero-io/kabanero-operator#765]
I have the default kabanero pipelines in my custom resource as shown below:

```yaml
    stacks:
      pipelines:
      - https:
          url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.1/default-kabanero-pipelines.tar.gz
        id: default
        sha256: 64aee2805d36127c2f1e0e5f0fc6fdae5cef19360c1bb506137584f3bd0988cc
      repositories:
      - https:
          url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.5/kabanero-stack-hub-index.yaml
        name: central
      - https:
          url: https://github.com/oiricaud/devops-demo-kabanero-pipelines/releases/download/v1.37/oiricaud-index.yaml
        name: typescript-angular
```
I have a new file named `temp.yaml` which is the following: 
```yaml
spec:
  stacks:
    pipelines:
      - https:
          url: https://github.com/oiricaud/pipeline-server/releases/download/59.0/default-kabanero-pipelines.tar.gz
        id: storefront-pipelines
        sha256: 64aee2805d36127c2f1e0e5f0fc6fdae5cef19360c1bb506137584f3bd0988cc

```
I then run `oc patch Kabanero/kabanero -p "$(cat json/temp.yaml)" --type=merge` but it doesn't merge both pipelines instead it replaces the pipeline as shown below:

```yaml
    stacks:
      pipelines:
      - https:
          url: https://github.com/oiricaud/pipeline-server/releases/download/59.0/default-kabanero-pipelines.tar.gz
        id: storefront-pipelines
        sha256: 64aee2805d36127c2f1e0e5f0fc6fdae5cef19360c1bb506137584f3bd0988cc
      repositories:
      - https:
          url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.5/kabanero-stack-hub-index.yaml
        name: central
      - https:
          url: https://github.com/oiricaud/devops-demo-kabanero-pipelines/releases/download/v1.37/oiricaud-index.yaml
        name: typescript-angular
```

Not sure if this is a `kubernetes` issue or if I am applying the patch incorrectly. Any insight would be nice.
