### ISSUE TITLE
kabanero-pipeline cannnot access AppsodyApplication in Kabanero namespace

### ISSUE THREAD

**Issue by haf-tech** [kabanero-io/kabanero-operator#770]
kabanero-pipeline cannnot access AppsodyApplication in Kabanero namespace
Similar to #702 , difference it is the `kabanero` namespace. 
Restart of the kabanero-operator pod did not solved the issue.

OCP 4.5
Kabanero 0.9.2

```
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  creationTimestamp: "2020-11-01T16:33:02Z"
  finalizers:
  - kabanero.io.kabanero-operator
  generation: 3
  name: kabanero
  namespace: kabanero
spec:
  admissionControllerWebhook: {}
  cliServices: {}
  codeReadyWorkspaces:
    enable: true
    operator:
      customResourceInstance:
        devFileRegistryImage: {}
        openShiftOAuth: true
        selfSignedCert: true
        tlsSupport: true
  collectionController: {}
  events: {}
  github: {}
  gitops: {}
  governancePolicy: {}
  landing: {}
  sso: {}
  stackController: {}
  stacks:
    pipelines:
    - https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.9.1/kabanero-events-pipelines.tar.gz
      id: default
      sha256: caf603b69095ec3d128f1c2fa964a2964509854e306fb3c5add8addc8f7f7b71
    repositories:
    - https:
        url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.9.0/kabanero-stack-hub-index.yaml
      name: central
  targetNamespaces:
  - demo-kabanero
  version: 0.9.2
status:
  admissionControllerWebhook:
    ready: "True"
  appsody:
    ready: "True"
    version: 0.5.1
  cli:
    hostnames:
    - kabanero-cli-kabanero.apps.cluster-6f68.sandbox389.opentlc.com
    ready: "True"
  codereadyWorkspaces:
    operator:
      instance:
        cheWorkspaceClusterRole: kabanero-codewind
        devfileRegistryImage: kabanero/che-devfile-registry:0.14.1
        openShiftOAuth: true
        selfSignedCert: true
        tlsSupport: true
      version: 2.4.0
    ready: "True"
  collectionController:
    ready: "True"
    version: 0.9.1
  events:
    ready: "True"
  gitops:
    ready: "True"
  kabaneroInstance:
    ready: "True"
    version: 0.9.2
  landing:
    ready: "True"
    version: 0.9.0
  serverless:
    knativeServing:
      ready: "True"
      version: 0.13.3
    ready: "True"
    version: 1.7.2
  sso:
    configured: "False"
    ready: "False"
  stackController:
    ready: "True"
    version: 0.9.1
  tekton:
    ready: "True"
    version: v0.11.3

```

Log from the deployment pipeline `build-push-promote-pl-...`

```
step-deploy-image
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "appsody.dev/v1beta1, Resource=appsodyapplications", GroupVersionKind: "appsody.dev/v1beta1, Kind=AppsodyApplication"
Name: "kabanero-nodejs-express", Namespace: "kabanero"
from server for: "/workspace/git-source/app-deploy.yaml": appsodyapplications.appsody.dev "kabanero-nodejs-express" is forbidden: User "system:serviceaccount:kabanero:kabanero-pipeline" cannot get resource "appsodyapplications" in API group "appsody.dev" in the namespace "kabanero"
```

Add-on
Main problem is, that in case no `app-deploy.yaml` is given, the application will be deployed in the default namespace, here `kabanero`. But it seems the sa has no permission to do so. One possible problem is that no rolebinding for the clusterrole `kabanero-pipeline-deploy-role` exists in the `kabanero` namespace.

After adding an `app-deploy.yaml` defining the target namespaces - as defined in the Kabanero CR and rolebinding exists also in this target namespace - does the deployment work.

Is this behavior a feature? ;-)
